#!/usr/bin/env bash
# Regenerate rules/dist/*.md — one pre-sliced rule file per level, for agents
# that take a static instructions file instead of running a hook.
#
# The slicing is done by hooks/laconic.sh itself rather than reimplemented here.
# There is one marker contract in this repo and it lives in the hook; a second
# awk pass would be a second thing to keep in sync, and the two drifting apart
# would ship users a rule file that does not match what the plugin delivers.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/rules/dist}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

mkdir -p "$OUT"
for level in lite full ultra; do
  printf '%s' "$level" > "$TMP/.laconic-level"
  {
    printf '<!-- Generated by tools/build-rules.sh from rules/laconic.md. Do not edit.\n'
    printf '     laconic level: %s. https://github.com/JordanMPDS/laconic -->\n\n' "$level"
    CLAUDE_CONFIG_DIR="$TMP" CLAUDE_PROJECT_DIR="$TMP" \
      bash "$ROOT/hooks/laconic.sh" start </dev/null
  } > "$OUT/laconic-$level.md"
done
